language: scala
scala:
- 2.12.4
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install jsdom
  - pip install --user awscli
script:
- sbt headerCheck test:headerCheck scalastyle test
after_script:
- $TRAVIS_BUILD_DIR/build/weigh.sh
- $TRAVIS_BUILD_DIR/build/upload.sh
