name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Scala
        uses: olafurpg/setup-scala@v2
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt seqexec_modelJVM/test seqexec_modelJS/test seqexec_engine/test seqexec_server/test seqexec_web_sharedJVM/test seqexec_web_sharedJS/test seqexec_web_server/test seqexec_web_client/test
